name: TechnologyFeedback
favicon: null
layout_spectrum: 0.8586649997159839
typography_spectrum: 0.7433202639222145
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23542984807863832
  lightness: 0.9687570736277848
  saturation: 0.6272592428140342
  rhythmicContrast: 0.7336825393140316
purpose: []
